# Generated by Django 4.1.3 on 2022-12-06 10:34

from django.db import migrations, models
import django.utils.timezone
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[users.validators.OlderOrEqualNine]),
            preserve_default=False,
        ),
    ]
